### ISSUE TITLE
Test `util::tests::test_global_timer` fails intermittently on CI

### ISSUE THREAD

**Issue by nrc** [tikv/client-rust#105]
Example output

```
thread 'util::tests::test_global_timer' panicked at 'assertion failed: timer.elapsed() >= ::std::time::Duration::from_millis(100)', src/util.rs:72:9

stack backtrace:

   0: backtrace::backtrace::libunwind::trace

             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88

   1: backtrace::backtrace::trace_unsynchronized

             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/mod.rs:66

   2: std::sys_common::backtrace::_print

             at src/libstd/sys_common/backtrace.rs:47

   3: std::sys_common::backtrace::print

             at src/libstd/sys_common/backtrace.rs:36

   4: std::panicking::default_hook::{{closure}}

             at src/libstd/panicking.rs:200

   5: std::panicking::default_hook

             at src/libstd/panicking.rs:214

   6: std::panicking::rust_panic_with_hook

             at src/libstd/panicking.rs:477

   7: std::panicking::begin_panic

             at /rustc/dddb7fca09dc817ba275602b950bb81a9032fb6d/src/libstd/panicking.rs:411

   8: tikv_client::util::tests::test_global_timer

             at src/util.rs:72

   9: tikv_client::util::tests::test_global_timer::{{closure}}

             at src/util.rs:66

  10: core::ops::function::FnOnce::call_once

             at /rustc/dddb7fca09dc817ba275602b950bb81a9032fb6d/src/libcore/ops/function.rs:235

  11: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once

             at /rustc/dddb7fca09dc817ba275602b950bb81a9032fb6d/src/liballoc/boxed.rs:770

  12: __rust_maybe_catch_panic

             at src/libpanic_unwind/lib.rs:80

  13: std::panicking::try

             at /rustc/dddb7fca09dc817ba275602b950bb81a9032fb6d/src/libstd/panicking.rs:275

  14: std::panic::catch_unwind

             at /rustc/dddb7fca09dc817ba275602b950bb81a9032fb6d/src/libstd/panic.rs:394

  15: test::run_test::run_test_inner::{{closure}}

             at src/libtest/lib.rs:1471

note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by sticnarf** [comment]
Close it by https://github.com/tikv/client-rust/pull/112.
